import type { Lang } from "@/lib/i18n";

export type ThemeKey =
  | "default" | "dark" | "midnight" | "lavender" | "crimson"
  | "forest" | "ocean" | "sunset" | "slate" | "rose";

export type Theme = {
  key: ThemeKey;
  label: string;
  isDark: boolean;
  preview: string; // tailwind gradient classes for the swatch
  vars: Record<string, string>;
};

/** All themes drive the same set of CSS variables. */
export const THEMES: Theme[] = [
  {
    key: "default",
    label: "Sky",
    isDark: false,
    preview: "from-sky-400 via-indigo-500 to-violet-600",
    vars: {
      "--bg":            "#eaf0fa",
      "--bg-elev":       "#f5f8fd",
      "--bg-hover":      "#dde6f5",
      "--bg-soft":       "#e3ecfb",
      "--border":        "#e5e7eb",
      "--text":          "#0f172a",
      "--text-muted":    "#64748b",
      "--text-subtle":   "#94a3b8",
      "--brand":         "#345fff",
      "--brand-strong":  "#1f3ff5",
      "--brand-soft":    "#dbe6ff",
      "--brand-on":      "#ffffff",
      "--accent":        "#7c3aed",
      "--danger":        "#e11d48",
      "--success":       "#10b981",
      "--shadow":        "0 1px 2px rgba(16,24,40,.04), 0 1px 3px rgba(16,24,40,.06)",
      "--shadow-pop":    "0 10px 30px rgba(16,24,40,.12)",
      "--scrollbar":     "#cbd5e1",
      "--ring":          "#5b86ff",
    },
  },
  {
    key: "dark",
    label: "Graphite",
    isDark: true,
    preview: "from-slate-700 via-slate-800 to-slate-950",
    vars: {
      "--bg":            "#0b0f17",
      "--bg-elev":       "#11151f",
      "--bg-hover":      "#1a2030",
      "--bg-soft":       "#1d2335",
      "--border":        "#1f2638",
      "--text":          "#e6e9f2",
      "--text-muted":    "#94a3b8",
      "--text-subtle":   "#64748b",
      "--brand":         "#7aa2ff",
      "--brand-strong":  "#5b86ff",
      "--brand-soft":    "#1a2350",
      "--brand-on":      "#0b0f17",
      "--accent":        "#a78bfa",
      "--danger":        "#fb7185",
      "--success":       "#34d399",
      "--shadow":        "0 1px 2px rgba(0,0,0,.4)",
      "--shadow-pop":    "0 10px 30px rgba(0,0,0,.6)",
      "--scrollbar":     "#2c3650",
      "--ring":          "#7aa2ff",
    },
  },
  {
    key: "midnight",
    label: "Midnight",
    isDark: true,
    preview: "from-indigo-700 via-blue-900 to-slate-950",
    vars: {
      "--bg":            "#0a0c1f",
      "--bg-elev":       "#0f1330",
      "--bg-hover":      "#161a3d",
      "--bg-soft":       "#1a204a",
      "--border":        "#1e2553",
      "--text":          "#e8ecff",
      "--text-muted":    "#9aa3d4",
      "--text-subtle":   "#6b73a8",
      "--brand":         "#8b9dff",
      "--brand-strong":  "#6979ff",
      "--brand-soft":    "#1f2766",
      "--brand-on":      "#0a0c1f",
      "--accent":        "#c084fc",
      "--danger":        "#fb7185",
      "--success":       "#34d399",
      "--shadow":        "0 1px 2px rgba(0,0,0,.5)",
      "--shadow-pop":    "0 10px 30px rgba(0,0,0,.7)",
      "--scrollbar":     "#2a3270",
      "--ring":          "#8b9dff",
    },
  },
  {
    key: "lavender",
    label: "Lavender",
    isDark: false,
    preview: "from-violet-300 via-purple-400 to-fuchsia-500",
    vars: {
      "--bg":            "#f4ecff",
      "--bg-elev":       "#fbf7ff",
      "--bg-hover":      "#ece2ff",
      "--bg-soft":       "#ece2ff",
      "--border":        "#e8defc",
      "--text":          "#2d1a52",
      "--text-muted":    "#6b5b8a",
      "--text-subtle":   "#9b8ec0",
      "--brand":         "#7c3aed",
      "--brand-strong":  "#6d28d9",
      "--brand-soft":    "#ede4ff",
      "--brand-on":      "#ffffff",
      "--accent":        "#d946ef",
      "--danger":        "#e11d48",
      "--success":       "#10b981",
      "--shadow":        "0 1px 2px rgba(76,29,149,.06), 0 1px 3px rgba(76,29,149,.08)",
      "--shadow-pop":    "0 10px 30px rgba(76,29,149,.18)",
      "--scrollbar":     "#d6c8f4",
      "--ring":          "#a78bfa",
    },
  },
  {
    key: "crimson",
    label: "Crimson",
    isDark: false,
    preview: "from-rose-400 via-red-500 to-orange-600",
    vars: {
      "--bg":            "#ffe9e9",
      "--bg-elev":       "#fff5f5",
      "--bg-hover":      "#ffd9d9",
      "--bg-soft":       "#ffd9d9",
      "--border":        "#ffd0d0",
      "--text":          "#3b0a0f",
      "--text-muted":    "#8a4a52",
      "--text-subtle":   "#b67e85",
      "--brand":         "#dc2626",
      "--brand-strong":  "#b91c1c",
      "--brand-soft":    "#ffe1e1",
      "--brand-on":      "#ffffff",
      "--accent":        "#f97316",
      "--danger":        "#9f1239",
      "--success":       "#10b981",
      "--shadow":        "0 1px 2px rgba(159,18,57,.06), 0 1px 3px rgba(159,18,57,.08)",
      "--shadow-pop":    "0 10px 30px rgba(159,18,57,.18)",
      "--scrollbar":     "#f5b8b8",
      "--ring":          "#f87171",
    },
  },
  {
    key: "forest",
    label: "Forest",
    isDark: false,
    preview: "from-emerald-400 via-green-500 to-teal-700",
    vars: {
      "--bg":            "#e6f5ec",
      "--bg-elev":       "#f3faf6",
      "--bg-hover":      "#d3edde",
      "--bg-soft":       "#d3edde",
      "--border":        "#cdebd9",
      "--text":          "#0a3a23",
      "--text-muted":    "#4f7864",
      "--text-subtle":   "#80a692",
      "--brand":         "#059669",
      "--brand-strong":  "#047857",
      "--brand-soft":    "#d1fae5",
      "--brand-on":      "#ffffff",
      "--accent":        "#0d9488",
      "--danger":        "#e11d48",
      "--success":       "#10b981",
      "--shadow":        "0 1px 2px rgba(6,95,70,.06), 0 1px 3px rgba(6,95,70,.08)",
      "--shadow-pop":    "0 10px 30px rgba(6,95,70,.18)",
      "--scrollbar":     "#b3dec3",
      "--ring":          "#34d399",
    },
  },
  {
    key: "ocean",
    label: "Ocean",
    isDark: false,
    preview: "from-cyan-400 via-sky-500 to-blue-700",
    vars: {
      "--bg":            "#e0f1ff",
      "--bg-elev":       "#f0f8ff",
      "--bg-hover":      "#cee6fa",
      "--bg-soft":       "#cce8ff",
      "--border":        "#c2e2fa",
      "--text":          "#0a2a4f",
      "--text-muted":    "#516f93",
      "--text-subtle":   "#7e9bbe",
      "--brand":         "#0284c7",
      "--brand-strong":  "#0369a1",
      "--brand-soft":    "#dbeefe",
      "--brand-on":      "#ffffff",
      "--accent":        "#06b6d4",
      "--danger":        "#e11d48",
      "--success":       "#10b981",
      "--shadow":        "0 1px 2px rgba(2,132,199,.06), 0 1px 3px rgba(2,132,199,.08)",
      "--shadow-pop":    "0 10px 30px rgba(2,132,199,.18)",
      "--scrollbar":     "#a8d4f4",
      "--ring":          "#38bdf8",
    },
  },
  {
    key: "sunset",
    label: "Sunset",
    isDark: false,
    preview: "from-amber-300 via-orange-500 to-pink-600",
    vars: {
      "--bg":            "#ffeed9",
      "--bg-elev":       "#fff7ec",
      "--bg-hover":      "#ffe2bd",
      "--bg-soft":       "#ffe2bd",
      "--border":        "#ffd9b3",
      "--text":          "#3f1d0a",
      "--text-muted":    "#8a5a3d",
      "--text-subtle":   "#b8896a",
      "--brand":         "#ea580c",
      "--brand-strong":  "#c2410c",
      "--brand-soft":    "#ffe7d3",
      "--brand-on":      "#ffffff",
      "--accent":        "#db2777",
      "--danger":        "#9f1239",
      "--success":       "#10b981",
      "--shadow":        "0 1px 2px rgba(234,88,12,.06), 0 1px 3px rgba(234,88,12,.08)",
      "--shadow-pop":    "0 10px 30px rgba(234,88,12,.18)",
      "--scrollbar":     "#f5c79a",
      "--ring":          "#fb923c",
    },
  },
  {
    key: "slate",
    label: "Slate",
    isDark: true,
    preview: "from-zinc-600 via-zinc-800 to-black",
    vars: {
      "--bg":            "#0a0a0a",
      "--bg-elev":       "#121212",
      "--bg-hover":      "#1c1c1c",
      "--bg-soft":       "#222222",
      "--border":        "#262626",
      "--text":          "#fafafa",
      "--text-muted":    "#a3a3a3",
      "--text-subtle":   "#737373",
      "--brand":         "#fafafa",
      "--brand-strong":  "#e5e5e5",
      "--brand-soft":    "#262626",
      "--brand-on":      "#0a0a0a",
      "--accent":        "#facc15",
      "--danger":        "#fb7185",
      "--success":       "#34d399",
      "--shadow":        "0 1px 2px rgba(0,0,0,.5)",
      "--shadow-pop":    "0 10px 30px rgba(0,0,0,.8)",
      "--scrollbar":     "#3a3a3a",
      "--ring":          "#fafafa",
    },
  },
  {
    key: "rose",
    label: "Rose",
    isDark: false,
    preview: "from-pink-300 via-rose-400 to-rose-600",
    vars: {
      "--bg":            "#ffe2ec",
      "--bg-elev":       "#fff0f5",
      "--bg-hover":      "#ffd2dd",
      "--bg-soft":       "#ffd2e1",
      "--border":        "#ffd2dd",
      "--text":          "#4a0e23",
      "--text-muted":    "#92516a",
      "--text-subtle":   "#bd819a",
      "--brand":         "#e11d48",
      "--brand-strong":  "#be123c",
      "--brand-soft":    "#ffd9e3",
      "--brand-on":      "#ffffff",
      "--accent":        "#a855f7",
      "--danger":        "#9f1239",
      "--success":       "#10b981",
      "--shadow":        "0 1px 2px rgba(225,29,72,.06), 0 1px 3px rgba(225,29,72,.08)",
      "--shadow-pop":    "0 10px 30px rgba(225,29,72,.18)",
      "--scrollbar":     "#f5b6c8",
      "--ring":          "#fb7185",
    },
  },
];

export const themeByKey = (k: string): Theme =>
  THEMES.find((t) => t.key === k) ?? THEMES[0];

export type Density = "comfortable" | "default" | "compact";
export type ReadingPane = "no-split" | "right" | "below";
export type InboxType = "default" | "important" | "unread" | "starred";

export type Preferences = {
  theme: ThemeKey;
  density: Density;
  readingPane: ReadingPane;
  inboxType: InboxType;
  conversationView: boolean;
  lang: Lang;
};

export const DEFAULT_PREFS: Preferences = {
  theme: "default",
  density: "default",
  readingPane: "right",
  inboxType: "default",
  conversationView: true,
  lang: "en",
};
